/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import DTOS.LibroDTO;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import Control.ControlNavegacion;

/**
 *
 * @author adoil
 */
//xd
//soy adolfo no sopas
public class GUIcarritoDetalle extends javax.swing.JPanel {

    private LibroDTO libro;
    private int cantidadEnCarrito;
    private GUICarrito carritoFrame;

    public GUIcarritoDetalle(LibroDTO libro, int cantidad, GUICarrito carritoFrame) {
        initComponents();
        this.libro = libro;
        this.cantidadEnCarrito = cantidad;
        this.carritoFrame = carritoFrame;
        mostrarLibroDetalle(libro,cantidad);
        
        if(BtnEliminar != null){
            BtnEliminar.setEnabled(cantidad > 0);
        }
    }

    
    private void mostrarLibroDetalle(LibroDTO libro,int cantidad) {
        lblTituloLibro.setText(libro.getTitulo());
        lblAutorLibro.setText(libro.getAutor());
        lblPrecioLibro.setText(String.format("%.2f", libro.getPrecio()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        LblAnioLibro.setText(dateFormat.format(libro.getFechaLanzamiento()));
        lblCantidad.setText("Cantidad: ");
        cantidadtxt.setText("Cantidad: ");
        
        cargarImagen(libro.getRutaImagen());
        
        if(cantidadtxt != null){
            cantidadtxt.setText(String.valueOf(cantidad));
        }
    }

    private void cargarImagen(String rutaImagen) {
         if (rutaImagen != null && !rutaImagen.isEmpty()) {
            try {
                java.net.URL imgUrl = getClass().getResource(rutaImagen);
                if (imgUrl != null) {
                     LblImagenSol.setIcon(new ImageIcon(imgUrl));
                } else {
                     System.err.println("Recurso no encontrado: " + rutaImagen);
                     LblImagenSol.setText("Imagen no encontrada");
                     LblImagenSol.setIcon(null);
                }
            } catch (Exception e) {
                System.err.println("Error al cargar la imagen: " + rutaImagen);
                e.printStackTrace();
                LblImagenSol.setText("Error al cargar");
                LblImagenSol.setIcon(null);
            }
        } else {
            LblImagenSol.setText("Sin imagen");
            LblImagenSol.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        PanelLasPruebasDelSol = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        LblImagenSol = new javax.swing.JLabel();
        lblTituloLibro = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        lblAutorLibro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrecioLibro = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        LblAnioLibro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cantidadtxt = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        PanelLasPruebasDelSol.setBackground(new java.awt.Color(217, 202, 218));
        PanelLasPruebasDelSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 196, 208), 2));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.MatteBorder(null));

        LblImagenSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LasPruebasDelSol1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(LblImagenSol, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblImagenSol, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloLibro.setText("...");

        BtnEliminar.setBackground(new java.awt.Color(102, 0, 102));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("-");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnAgregar.setBackground(new java.awt.Color(102, 0, 102));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI Black", 3, 20)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("+");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        lblAutorLibro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAutorLibro.setText("...");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel4.setText("titulo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel6.setText("Precio:");

        lblPrecioLibro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPrecioLibro.setText("...");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel7.setText("Autor:");

        lblCantidad.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblCantidad.setText("Cantidad");

        LblAnioLibro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        LblAnioLibro.setText("...");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel9.setText("Año:");

        cantidadtxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cantidadtxt.setText("...");

        javax.swing.GroupLayout PanelLasPruebasDelSolLayout = new javax.swing.GroupLayout(PanelLasPruebasDelSol);
        PanelLasPruebasDelSol.setLayout(PanelLasPruebasDelSolLayout);
        PanelLasPruebasDelSolLayout.setHorizontalGroup(
            PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioLibro))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloLibro))
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblAutorLibro))
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(LblAnioLibro))
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidadtxt)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        PanelLasPruebasDelSolLayout.setVerticalGroup(
            PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPrecioLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAutorLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LblAnioLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(cantidadtxt))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLasPruebasDelSol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLasPruebasDelSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        System.out.println("Desea eliminar una copia del libro: " + libro.getTitulo());
        if(libro != null && carritoFrame != null){
            ControlNavegacion.getInstase().eliminarLibroCarrito(this.libro);
            carritoFrame.actualizarListaCarrito();
        }else{
            System.err.println("Error al intentrar eliminar una copia del libro");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        System.out.println("Desea agregar otra copia del libro: " + libro.getTitulo());
        if(libro != null && carritoFrame != null){
            ControlNavegacion.getInstase().agregarLibroCarrito(this.libro);
            carritoFrame.actualizarListaCarrito();
        }else{
            System.err.println("Error al intentrar agregar otra copia del libro");
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JLabel LblAnioLibro;
    private javax.swing.JLabel LblImagenSol;
    private javax.swing.JPanel PanelLasPruebasDelSol;
    private javax.swing.JLabel cantidadtxt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblPrecioLibro;
    private javax.swing.JLabel lblTituloLibro;
    // End of variables declaration//GEN-END:variables
}
